import { Metadata } from "next";
import React from 'react'
import HalamanLogin from "@/components/HalamanLogin";
import { useSession } from "next-auth/react";


export const metadata: Metadata = {
  title: "Login Page",
  description: "Generated by Ridwan",
};

export default function page() {
  return (
  <HalamanLogin/>
  )
}
