import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import NotAuthorized from "@/components/NotAuthorized";
import Sidebar from "../../components/sidebar";
import TopBar from "../../components/TopBar";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Dashboard Admin BVK",
  description: "Generated by Ridwan",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  if (!session) {
    return <NotAuthorized />;
  }

  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Sidebar />
          <div className="flex-1">
            <TopBar
              name={session.user?.name as string}
              image={session.user?.image as string}
            />
            <main className="p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
